typedef enum {
   VTPARSE_STATE_CSI_ENTRY = 1,
   VTPARSE_STATE_CSI_IGNORE = 2,
   VTPARSE_STATE_CSI_INTERMEDIATE = 3,
   VTPARSE_STATE_CSI_PARAM = 4,
   VTPARSE_STATE_DCS_ENTRY = 5,
   VTPARSE_STATE_DCS_IGNORE = 6,
   VTPARSE_STATE_DCS_INTERMEDIATE = 7,
   VTPARSE_STATE_DCS_PARAM = 8,
   VTPARSE_STATE_DCS_PASSTHROUGH = 9,
   VTPARSE_STATE_ESCAPE = 10,
   VTPARSE_STATE_ESCAPE_INTERMEDIATE = 11,
   VTPARSE_STATE_GROUND = 12,
   VTPARSE_STATE_OSC_STRING = 13,
   VTPARSE_STATE_SOS_PM_APC_STRING = 14,
   VTPARSE_STATE_UTF8_2 = 15,
   VTPARSE_STATE_UTF8_3 = 16,
   VTPARSE_STATE_UTF8_3_1 = 17,
   VTPARSE_STATE_UTF8_3_E0 = 18,
   VTPARSE_STATE_UTF8_3_ED = 19,
   VTPARSE_STATE_UTF8_4 = 20,
   VTPARSE_STATE_UTF8_4_1 = 21,
   VTPARSE_STATE_UTF8_4_2 = 22,
   VTPARSE_STATE_UTF8_4_F0 = 23,
   VTPARSE_STATE_UTF8_4_F4 = 24,
} vtparse_state_t;

typedef enum {
   VTPARSE_ACTION_CLEAR = 1,
   VTPARSE_ACTION_COLLECT = 2,
   VTPARSE_ACTION_CSI_DISPATCH = 3,
   VTPARSE_ACTION_ESC_DISPATCH = 4,
   VTPARSE_ACTION_EXECUTE = 5,
   VTPARSE_ACTION_HOOK = 6,
   VTPARSE_ACTION_IGNORE = 7,
   VTPARSE_ACTION_OSC_END = 8,
   VTPARSE_ACTION_OSC_PUT = 9,
   VTPARSE_ACTION_OSC_START = 10,
   VTPARSE_ACTION_PARAM = 11,
   VTPARSE_ACTION_PRINT = 12,
   VTPARSE_ACTION_PUT = 13,
   VTPARSE_ACTION_UNHOOK = 14,
   VTPARSE_ACTION_ERROR = 15,
} vtparse_action_t;

typedef unsigned state_change_t;
extern state_change_t STATE_TABLE[24][256];
extern vtparse_action_t ENTRY_ACTIONS[24];
extern vtparse_action_t EXIT_ACTIONS[24];
extern char *ACTION_NAMES[16];
extern char *STATE_NAMES[25];

